site_name: SMPL-X Toolbox
site_description: Developer utilities for SMPL/SMPL-H/SMPL-X models
site_url: https://yourusername.github.io/smplx-toolbox

repo_url: https://github.com/yourusername/smplx-toolbox
repo_name: yourusername/smplx-toolbox

theme:
  name: material
  features:
    - navigation.sections
    - navigation.path
    - navigation.instant
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            show_root_heading: true
            show_root_toc_entry: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Core:
      - Unified Model: core/unified_model.md
      - Data Containers: core/containers.md
      - SMPL-X Adapter: core/smplx_model.md
      - SMPL-H Adapter: core/smplh_model.md
  - CLI: cli.md

